# Generated by Django 5.1.7 on 2025-09-30 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cee', '0002_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='first_name',
            new_name='First_name',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='last_name',
            new_name='Last_name',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='Message',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='subject',
            new_name='Subject',
        ),
    ]
