# Generated by Django 5.1.7 on 2025-07-22 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Folio',
        ),
    ]
