# Generated by Django 5.1.7 on 2025-08-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_info_remove_comment_article_remove_comment_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='organization_name',
        ),
        migrations.AddField(
            model_name='info',
            name='instructions',
            field=models.TextField(default='what is your project about'),
        ),
        migrations.AlterField(
            model_name='info',
            name='services',
            field=models.CharField(choices=[('Web_design', 'Web_design'), ('Web_development', 'Web_development'), ('Test_usability', 'Test_usability')], default='Web_design', max_length=20),
        ),
    ]
