# Generated by Django 5.1.7 on 2025-08-20 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_remove_info_organization_name_info_instructions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='instructions',
            field=models.TextField(default='What is your project about?'),
        ),
    ]
