# Generated by Django 5.1.7 on 2025-08-21 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_info_instructions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='instructions',
            new_name='your_project',
        ),
    ]
