# Generated by Django 5.1.7 on 2025-09-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_rename_instructions_info_your_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='your_project',
            field=models.TextField(),
        ),
    ]
