# Generated by Django 5.1.7 on 2025-10-11 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_portfolio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='your_project',
            new_name='message',
        ),
    ]
